name: Build and Publish

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      os:
        description: "OS to build (ubuntu, macos, windows, or all)"
        required: false
        default: "all"
      publish_target:
        description: "Where to publish (testpypi or pypi)"
        required: false
        default: "testpypi"

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON('["ubuntu-latest","windows-latest","macos-latest"]') }}
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.os == 'all' || matrix.os == github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install cibuildwheel build

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*

  publish:
    name: Publish to PyPI/TestPyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        if: ${{ github.event.inputs.publish_target == 'pypi' }}

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
