name: Build and Publish Wheels

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.18

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-wheels
          path: ./wheelhouse/*.whl
          
  publish:
    name: Publish to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    
    # Add this block to grant OIDC token permissions for this job
    permissions:
      id-token: write
      
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          name: cibuildwheel-wheels
          path: ./dist
          
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./dist
