name: Build and Publish Wheels
on: workflow_dispatch

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or specify the range of versions you support
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18
        env:
          CIBW_BUILD: "cp311-* cp314-*" # Example to build for CPython 3.11 and 3.14
          CIBW_SKIP: "*-musl"
      - uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-wheels
          path: ./wheelhouse/*.whl

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cibuildwheel-wheels
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
