name: Build and Publish Wheels (Ubuntu)

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install build dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build wheel twine

        - name: Build wheels
          run: |
            python -m build --wheel

        - name: Publish to TestPyPI
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          run: |
            python -m twine upload --repository testpypi dist/*